name: Integration Test

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "testing" ]
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # 支持 Linux 和 Windows
        python-version: [3.10, 3.12]  # 测试 Python 3.10 和 3.12
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            pip install -r requirements.txt
          else
            pip install -r requirements_windows.txt
          fi

      - name: Create .env file
        run: echo "ASSETS_PATH=./" > .env

      - name: Run main.py
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            nohup python main.py &
          else
            start /min python main.py
          fi
        shell: bash

      - name: Test API
        run: pytest
        shell: bash
